name: Deploy
on:
  workflow_run:
    workflows: [Lighthouse CI]
    types: [completed]
jobs:
  on-success:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: lighthouse.yml
          workflow_conclusion: success
          name: build-result
          path: .
      - name: Deploy to release branch
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: release
          FOLDER: dist
