name: Run Lighthouse CI
on:
  push:
    branches:
      - 'main'
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install, build
        run: |
          yarn install
          yarn build
      - name: run Lighthouse CI (mobile)
        run: |
          yarn global add @lhci/cli@0.8.x
          lhci autorun --upload.target=temporary-public-storage --assert.preset=lighthouse:no-pwa
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: run Lighthouse CI (desktop)
        run: |
          lhci autorun --upload.target=temporary-public-storage --assert.preset=lighthouse:no-pwa --collect.settings.preset=desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
